### ISSUE TITLE
Make diagnostics optional too

### ISSUE THREAD

**Issue by sakhnik** [natebosch/vim-lsc#100]
How could I disable automatic diagnostics highlight?
I'd like to keep the navigation, but let diagnostic be done by another plugin.

**Comment by natebosch** [comment]
The easiest thing to do will be an option that makes the client ignore any diagnostics sent by the server, which means they won't be highlighted, won't show up in the location list, won't be echoed when the cursor moves around, and nothing will appear with `:LSClientAllDiagnostics`. I think that should satisfy this request, please let me know if it doesn't and you'd prefer to disable specifically the highlighting while leaving some or all of the rest of the functionality.

**Comment by natebosch** [comment]
Try adding `let g:lsc_enable_diagnostics = v:false` and see how it works for you.

**Comment by sakhnik** [comment]
It's fine for me. Thanks!

**Comment by natebosch** [comment]
@andymass - there is not option today, what is the use case?

Note that the protocol does not specify a way for the client to request diagnostics. You wouldn't be able to request an update to diagnostics, or keep them static in between requests, but what we could do is still track diagnostics and allow you to flip their effects - highlights and location list - on and off.

You'd pay a small performance penalty for collecting them even when not using them. I don't think this should hurt much.

Let me know your use case and I'll think about how we might support this.

**Comment by andymass** [comment]
@natebosch very sorry for the delay and thank you for explaining how this relates to the design of the language server protocol.

My use-case is that the majority of the time when I open a file I don't want to see the noisy diagnostics.  (Honestly, this is probably down to me mis-configuring the language server.)  Occasionally, I would like to turn them on, similar to an explicit lint or compile.   I think your suggestion of simply hiding them in an easily toggleable way would be totally acceptable (in addition to the existing enable_diagnostics option).  However, I admit it seems like somewhat low priority due to overlap with existing tools, and is possibly difficult to implement.

**Comment by natebosch** [comment]
I'm going to add in `let g:lsc_enable_highlights = v:false` as well as `:LSClientEnableHighlights` and `:LSClientDisableHighlights`. My current thinking is that this same config would also control the `echo` of the diagnostic messages when the cursor is on the same line as a diagnostic. If someone wants to enable that without highlights (or disable that and keep higlights) I could also add a second config option, but my guess is that most folks who won't want highlights wont want the echo either.
