### ISSUE TITLE
Support manual omnicomplete completion

### ISSUE THREAD

**Issue by cbracken** [natebosch/vim-lsc#15]
It would be awesome to be able to have a setting to allow disabling autocomplete on `.` and instead support wiring up to manual omni-complete on `C-x, C-o`.

**Comment by natebosch** [comment]
Will need to make a couple decisions:

1. Should completion switch back to `omnifunc` from calling `complete()`? `omnifunc` would make it easier to implement fuzzy completion later on since it can ask to be re-called after the next typed character, whereas with `complete()` the next character needs to be monitored manually. It would also make this configuration easier.
2. Should suggestions be fetched eagerly or wait for the completion request?

Took a quick look and I don't think there is an easy way to address this - I'll give it some more thought.

**Comment by natebosch** [comment]
This turned out to be a bit easier than I had anticipated. I left the 'auto' behavior using `complete()` and added an option to use a `completefunc` instead.

Behavior feels mostly OK to me, but I only played around with it for a little bit in a small project. If completion suggestions get slower from the server this might not work as well. It currently relies on the server responding with results before requesting completion - if you happen to beat the server it'll just cancel out of the completion with no indication. Completion also only works after typing 3 characters in a name, or after a `.` - It won't complete variable names before 3 characters are typed for instance.

The README shows a configuration using `completefunc` but `omnifunc` should work just as well. Complete with `<c-x><c-u>` or <c-x><c-o>` (or `<c-x><c-n>` etc) depending on your configuration. In this code path the `completeopts` aren't touched so you may want to add `menuone,noinsert` to get closer behavior to before with a manual trigger.

Give it a shot and let me know what you think. I've got a few ways I think it could have better ergonomics but if these aren't important I probably won't bother:

- Configuration of `completefunc` (or `omnifunc`) could be handled by the plugin so it only happens for the filetypes that matter.
- Could set it up so that requesting completion before we have results will bail out - then when the results come in follow the 'auto' codepath and pop up the menu. This could let us support things like requesting completion before typing 3 characters in a variable name.
- Could give a better indication of what is happening when we don't have results etc - right now you can't tell if there are just no results, or if the server didn't respond.

**Comment by cbracken** [comment]
Works beautifully for me. Thanks! 

> Configuration of completefunc (or omnifunc) could be handled by the plugin so it only happens for the filetypes that matter.

I think it's reasonable to expect the user configure this in their vimrc with the appropriate `au` commands. You could provide an example in the README file. I admit my personal preference is pretty minimalist with explicit config for stuff though, and I'm not sure where that puts me on the spectrum of vim users :)

**Comment by natebosch** [comment]
As an FYI I did end up implementing support to automatically set the `completefunc`, and/or mappings for the commands, only in the relevant buffers: https://github.com/natebosch/vim-lsc/commit/2a25afdce755cf5748a36963f1ed0d2d7286178f

It's 100% opt in so feel free to ignore it if you're happy with what you have.
