### ISSUE TITLE
Is the length of the autocomplete trigger editable?

### ISSUE THREAD

**Issue by timtraversy** [natebosch/vim-lsc#171]
Can we change the default number of chars (3) that trigger autocomplete? In IDEs like IntelliJ it's closer to 1 or 2. Would this cause performance issues?

**Comment by natebosch** [comment]
It's not editable today, but only because no one asked for it and I have it set to something I like 😄 

I could add a setting for this, or I could try bumping down the default. I don't know if we can generalize whether or not it'll be a performance problem.

Do you think the setting should be global, or should it be specific to each server you have configured?

**Comment by timtraversy** [comment]
I only use this for Dart but I feel like a global preference makes sense.

**Comment by timtraversy** [comment]
https://github.com/natebosch/vim-lsc/blob/b02690e167a1b49373245aabbedecd29aa470309/autoload/lsc/complete.vim#L73-L82

Is this the relevant code?

**Comment by natebosch** [comment]
Yup, that's where we need to make the adjustment

**Comment by natebosch** [comment]
@timtraversy - please update to the latest and try `let g:lsc_autocomplete_length = 1` in your vimrc. Let me know if it causes any trouble for you.

**Comment by natebosch** [comment]
Its possible for the server to not be sending any results if there are too few characters, or maybe for it to be slower.

It's working for me - can you doublecheck the spelling on the setting and ensure you're on the latest?

[![asciicast](https://asciinema.org/a/pmn1V25sww1mcjwhywYG8hZu6.svg)](https://asciinema.org/a/pmn1V25sww1mcjwhywYG8hZu6)

**Comment by timtraversy** [comment]
Working for me! I may have just not updated 😀
