### ISSUE TITLE
Preview window is always empty.

### ISSUE THREAD

**Issue by Tinee** [natebosch/vim-lsc#207]
Hey Nate!
So I'm having some issues when using autocompletion with this language server.

**Information**:
- Language: Go
- Vim version: 8.1.1850
- vimrc: [here](https://gist.github.com/Tinee/f8a74917aa6f5877fdd83dfd2a103730)

**Expected**
<img width="411" alt="Screen Shot 2019-08-21 at 15 03 33" src="https://user-images.githubusercontent.com/16955389/63399530-ec124d80-c424-11e9-8d45-82ac4908c822.png">

but this can only be achieved by leaving insert mode and then hitting `gm`.

**Actual**
<img width="603" alt="Screen Shot 2019-08-21 at 14 55 40" src="https://user-images.githubusercontent.com/16955389/63399316-465ede80-c424-11e9-9926-73e0d7bb6a26.png">
This is what I see which is fine if it wasn't for the fact that as soon as I start typing the popover-window disappear (see picture below).
 
<img width="430" alt="Screen Shot 2019-08-21 at 15 00 20" src="https://user-images.githubusercontent.com/16955389/63399459-b705fb00-c424-11e9-9010-a48b33b5f6b2.png">

Not sure what causes these issue and by looking at my vimrc I can't imagine any of my settings or plugins clash with this language server.

**Comment by xuanduc987** [comment]
>  **g:lsc_hover_popup**
>
> When the |popup| feature is available it will be used for `:LSClientShowHover`
 >by default. Restore the old behavior of using the |preview-window| by setting
 >`g:lsc_hover_popup` to `v:false`.

So to show method signature in preview windows you must set
`let g:lsc_hover_popup = v:false`

**Comment by natebosch** [comment]
The signature help still always opens in the preview window - I may investigate having that show in the popup instead but I think that would actually make this behavior even worse for you.

The "actual" looks like it's showing the autocomplete popup menu, and an empty preview window. You should see information in the preview window on autocomplete as long as your language server is populating the `'documentation'` field on the completion items.

https://github.com/natebosch/vim-lsc/blob/9beabedbade88e591b420ee8fb38e5621fd0cc7f/autoload/lsc/complete.vim#L274-L280

The fact that it becomes blank indicates that your server isn't sending `'documentation'`. If you first use `gm` to get signature help, we will blow away the preview window content when you autocomplete because we set it to an empty string by default.

https://github.com/natebosch/vim-lsc/blob/9beabedbade88e591b420ee8fb38e5621fd0cc7f/autoload/lsc/complete.vim#L273

It's had the `info` field defaulting for a long time, but I didn't write down why I made that choice - it could have been arbitrary. I'll see if it would make sense to avoid this blank string.

**Comment by natebosch** [comment]
I couldn't find any major drawbacks to _not_ setting an empty info when there is no documentation so I made a change there. This should at least let you keep the preview window as whatever it is before you the autocomplete starts.

As for the deeper problem of expecting something to show up during autocomplete, I'm not sure if it makes sense to shoehorn in something else other than the documentation. You could check the communication with the server to verify it isn't sending documentation, and maybe file a feature request on the server to add it.

See https://github.com/natebosch/vim-lsc/wiki/Server-Debugging-Tips#logging-communication-across-stdio for some tips on logging the communication, or try `:echo lsc#server#current()[0]._channel._out[-5:]` to see the most recent 5 messages from the server after an autocomplete happens.

**Comment by Tinee** [comment]
> `let g:lsc_hover_popup = v:false`
Worked like a charm to get everything to come down to the preview-window. Thanks!

**Comment by natebosch** [comment]
Closing since the existing config option was enough.
