### ISSUE TITLE
Add autocommand to report diagnostics changed

### ISSUE THREAD

**Issue by pwntester** [natebosch/vim-lsc#227]
I would like to be notified when diagnostics have changed so I can update my statusbar. This is something I was doing with languageClient-neovim using the `LanguageClientDiagnosticsChanged` autommand:

```
autocmd User LanguageClientDiagnosticsChanged call lightline#update()
```

I think it would be useful to add a similar autocommand.

Thanks

**Comment by natebosch** [comment]
This should be feasible. The only question is whether we want any filtering.

Should we trigger this when _any_ diagnostic update is received? This might get triggered frequently shortly after startup for some servers that send diagnostics for every file in a workspace.

Or should we filter this and only trigger if a diagnostic update is received for an open file?

I'm leaning towards the former since I imagine the use case is something like a total number of errors display, and that should generally apply across a workspace?

**Comment by natebosch** [comment]
@pwntester - can you check the PR https://github.com/natebosch/vim-lsc/pull/228 and see if it works for you?

**Comment by pwntester** [comment]
Works great thanks!
This can also be used to cutomize diagnostics visualization (eg: virtual text, gutter signs, etc)
