### ISSUE TITLE
Need to press <enter> three times for new line

### ISSUE THREAD

**Issue by floitsch** [natebosch/vim-lsc#244]
When using the vim-lsp plugin, we sometimes need to press `<enter>` three times to get a new line.
This happens when there is a completion item.
Say we have:
```
x := nul
```
At this point completion suggests `null` as completion item.
After finishing writing `null`, I want to get to the next line with `<enter>`.
However it takes two presses of `<enter>` to just remove the completion suggestions, and then finally a third `<enter>` to get to the next line.

There could be an issue with the language server, but to me the interaction looks ok. (I still attached the in/out logs).

Alternatively, we might just miss a configuration, but maybe it would then be interesting to change the default to something that doesn't trigger this issue.

[lsp_in-2019-12-04 13:06.11 UTC.log](https://github.com/natebosch/vim-lsc/files/3921934/lsp_in-2019-12-04.13.06.11.UTC.log)
[lsp_out-2019-12-04 13:06.11 UTC.log](https://github.com/natebosch/vim-lsc/files/3921935/lsp_out-2019-12-04.13.06.11.UTC.log)

/cc @erikcorry

**Comment by bluz71** [comment]
I assume you mean the vim-lsc plugin, not vim-lsp?

If so, which programming language?

Can you comment all plugins you are using, except vim-lsc. Does the issue persist?

It is likely you have a plugin which has an insert mode mapping for CR, I had similar issues to yours with Tim Pope's Endwise plugin.

**Comment by floitsch** [comment]
Yes, I mean the vim-lsc plugin.
The programming language is toit, but the LSP server isn't yet open-sourced. However, if you look at the attached lsp_out (in the first post), you can see that the completion answer looks very much non-problematic.

I will try to see if there is another plugin that interferes, but I'm not a heavy plugin user, so it's unlikely that any of those plugins is responsible. Also of note: my coworker runs into the same issue, and uses a completely different setup (Ubuntu vs Arch, gvim vs vim, ...).
I will try to have a look on Monday. If you have tips to ensure that only the vim-lsc plugin runs, please let me know.

**Comment by bluz71** [comment]
vim-lsc, from my understanding, is not in the picture at the time `nul` has been typed and the completion menu is visible (and static). When `<CR>` is typed, that should eliminate the completion popup, and the next `<CR>` should result in a newline. That you need three `<CR>` is very likely due to a mapping issue.

The symptom you describe in the first post, matches a very similar issue I had with [vim-endwise](https://github.com/tpope/vim-endwise) and LSC, that plugin creates an Insert mode mapping for `<CR>`. Auto-pairs plugins also can create insert mappings for `<CR>`.  In my case I had to work around those issues myself.

So I suggest again, please comment out all plugins you have apart from `vim-lsc` and see if the triple Enter persists. I expect a functioning setup to require two Enters, the first to close the popup and the 2nd does the actual newline.

Actually, now that I think about it, please first list your insert mode mappings:

```viml
:imap
```

See if there `<CR>` mapping?

**Comment by floitsch** [comment]
Thanks. Will do it (hopefully) on Monday.
Slightly off-topic: do you maybe know how to make completion selection be on <tab> instead of <enter>. That would be a much better solution overall. (Although I would still try to figure out why one needs 3 enters).

**Comment by bluz71** [comment]
> Slightly off-topic: do you maybe know how to make completion selection be on instead of .

Sorry, I don't understand what you are asking here?

Once the completion menu is visible, LSC is no longer in the picture, rather standard Vim completion will be in effect. LSC populates the menu, but the behaviour will be determined by Vim's completion settings.

However, I understand that LSC sets `completeopt=menu,menuone,noinsert,noselect`. So maybe it is worth looking at what those values do for you.

Most autocompletion plugins set `completeopt` to those values (ALE does).

**Comment by floitsch** [comment]
Haven't yet figured out if there are other plugins running, but I can already report the `:imap` results: "No mapping found".

Also, I wrote a really simple LSP server, that reproduces locally for me.
Just write (on the first line): `null`.
After the third character, the completion should kick in and propose "null" as completion.
Finish writing "null". Then press "enter".  The first `<enter>` doesn't do anything.
With the second one, it removes the `null` completion, and then the third one makes it go to the new line.
I'm still trying to see if there is something weird with my setup, but if you can't reproduce with the fake-server, we can at least be sure that this is a problem on my side and close the bug.

Launch fake-server with `dart <full_path_to_fake_lsp>/lsp.dart`
[fake_lsp.zip](https://github.com/natebosch/vim-lsc/files/3939894/fake_lsp.zip)

**Comment by floitsch** [comment]
> > Slightly off-topic: do you maybe know how to make completion selection be on instead of .
> 
> Sorry, I don't understand what you are asking here?
Sorry. Github ate the `<` and `>` around `<tab>` and `<enter>`. I updated my comment.
This is probable a pum setting, so nothing that is really relevant to this bug. (but if you happen to know, please let us know :)

**Comment by bluz71** [comment]
@floitsch,

I just tested with your LSP fake-server.

```
x := nul
```

After `l` is typed, the completion popup appears with `null`.

First `<CR>` closes the popup.
Second `<CR>` inserts a newline.

Only two enters required.

I am confident the issue relates to your setup, likely a plugin adding in a mapping for `<CR>`, like Endwise and Auto-Pairs do.

I suggest stripping your setup right back and see what happens.

**Comment by bluz71** [comment]
Aha, actually, I can now repeat your issue with your fake-server.

It is required that you type `l` after `nul`, as you said. I was doing the `<CR>` immediately after `nul`, not `null`.

This behaviour also happens with other LSP servers with other languages.

I never encountered this since I always use tab (which maps to Ctrl-n) to complete from the available options or the language itself uses semi-colons which then outcloses the popup.

After playing, LSC appears to be doing some async processing to fill in the popup list and is not treating `<CR>` as a word/popup delimiter. 

If you did type `nul`, popup, `l;`, `<CR>` the issue does not happen due to the semi-colon.

I can see that it is annoying for you. This mapping may be useful to you:

```viml
imap <expr> <CR> (pumvisible() ? "\<C-e>\<CR>" : "\<CR>")
```

Nate probably has enough information now to repeat it locally and see if it worth doing anything about this.

**Comment by floitsch** [comment]
Thanks for looking into this.
I will try to solve the issue by finding a good remapping.

**Comment by natebosch** [comment]
I did track down a bug here.

It is expected that you'd need to hit enter twice for a newline, see `:help popupmenu-keys`. The first press is selecting an item (which happens to match the existing text in this example) and leaves completion mode. The second inserts a newline.

It's not expected that you'd have to hit enter 3 times. The reason this is happening is that I have a bug where after picking a completion, we get a trigger that the text has changed and then try to treat it as if you typed a character and enter a new round of completing.

**Comment by bluz71** [comment]
Excellent.

**Comment by floitsch** [comment]
Thanks!
