### ISSUE TITLE
[lsc:Error] File URI did not contain a valid file path

### ISSUE THREAD

**Issue by habamax** [natebosch/vim-lsc#249]
Whenever I open dart file I get this message and nothing related to language server works.

![image](https://user-images.githubusercontent.com/234774/68532429-0fff7400-032e-11ea-84b3-d20320e119f0.png)

Could you point me where can I try to look/search in the code to find the root cause?

Gvim/Vim on Windows 10.
Dart is installed using scoop (version 2.6.0)
I can run dart lsp with the `dart snapshot/blabla --lsp`.

**Comment by natebosch** [comment]
Moving to the `vim-lsc` repo since that is where the bug is.

@habamax - can you try out the branch in https://github.com/natebosch/vim-lsc/pull/248 and see if it works for you? My initial testing looks good, but since I don't use windows day to day I'm not sure if there are some edge cases I missed.

**Comment by DanTup** [comment]
> So it seems this is at least somewhat intended. I'm not sure what the best solution is here, my intuition is that if we end up with such a file we should analyze anyway.

That would be ideal, but the server doesn't currently support analyzing loose files (https://github.com/dart-lang/sdk/issues/32256):

https://github.com/dart-lang/sdk/blob/4043a6fce3447428fe3b3d1a7d2098ac0311f4d3/pkg/analysis_server/lib/src/lsp/handlers/handler_text_document_changes.dart#L142

This message was somewhat of a workaround because of that. It's a limitation of the server (not the LSP layer) so I'm not sure how involved handling that would be.

**Comment by natebosch** [comment]
I think this is fixed by https://github.com/natebosch/vim-lsc/pull/248

@habamax - please update to the latest vim-lsc and let me know if you continue to have this problem.

**Comment by ondal4** [comment]
It's a very old topic. I ran into this on Linux. The vim I opened on the desktop did not work. It worked when I changed it. Maybe it'll be of use to someone. It might have something to do with security. But I know very little.
