### ISSUE TITLE
No scala configuration example

### ISSUE THREAD

**Issue by philliptaylorpro** [natebosch/vim-lsc#254]
[This wiki page](https://github.com/natebosch/vim-lsc/wiki/Language-Servers) details how to configure each language to use vim-lsc. For Scala you link to the scala-metals wiki, but they have updated their pages to use a rival plugin, coc.vim. So now there are no details on how to configure vim-lsc with Scala and you're indirectly redirecting users away.

**Comment by natebosch** [comment]
Looks like they removed it here:
https://github.com/scalameta/metals/commit/f426df61a2e32f292c2ca52cec07435a957f7bc4#diff-906ca6593f8febd23e01ed6a23c8722aL74

The old docs mention `-Dmetals.client=vim-lsc` - I might need to check in to whether that still exists, then figure out the best place to link for docs on compile and installing the server with that flag.

I think the client side config _should_ be as simple as

```viml
let g:lsc_server_commands = {
  \  'scala': {
  \    'command': 'metals-vim',
  \    'log_level': 'Log'
  \  }
  \}
```

If anyone is using this server and can comment on the installation process I'd appreciate it.

**Comment by jqno** [comment]
I'm using it occasionally, I simply have this:
```
let g:lsc_server_commands = {
  \ 'scala': 'metals-vim'
  \ }
```

The `Dmetals.client=vim-lsc` thing is so they can add some special case code for specific clients. You can see the special code [here](https://github.com/scalameta/metals/blob/feec5dba097d0a16774d02be0c58dfd42f16c9e0/metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala#L111). Not sure how important that actually is, though: you can probably leave it out if you want, though I haven't tried. Anyway, you have to pass that parameter when you compile `metals` locally. Look [here](https://scalameta.org/metals/docs/editors/vim.html#using-an-alternative-lsp-client) for more info.

**Comment by ckipp01** [comment]
I went ahead and updated the wiki to have a bit more instructions about how to bootstrap Metals correctly, and also to include the simple setting that @jqno mentioned since that's what I use as well.

Regarding the `Dmetals.client=vim-lsc`, depending on the client, it's pretty important. However, I took at look at what we had for `vim-lsc` and I did include a change in a pr that I had open https://github.com/scalameta/metals/pull/1289/files#r365694293 since I think that users need some sort of feedback while using `vim-lsc` and metals, so it's important the messages are being shown.

If there is anything else that you think would serve the docs well or if the default `vim-lsc` settings should be updated with something else, please don't hesitate to ping me, and I'm happy to look into it.

**Comment by natebosch** [comment]
Looks good to me! Thanks for updating the wiki!

I'll close this for now and we can revisit if the updated example on the wiki stops working.
