### ISSUE TITLE
'suppress_stderr' no longer suppressed since commit 22ad743

### ISSUE THREAD

**Issue by bluz71** [natebosch/vim-lsc#290]
Hello Nate,

It seems [commit 22ad743](https://github.com/natebosch/vim-lsc/commit/22ad7433b35b194015856d5b41037b752e192764) broke the `suppress_stderr` option.

Notice the command line area now.

<img width="727" alt="Startup-Error" src="https://user-images.githubusercontent.com/11382509/83345368-9d032c80-a355-11ea-8424-98b8149ac69b.png">

My Ruby configuration is:

```viml
let g:lsc_server_commands = {
 \  'ruby': {
 \    'command': 'solargraph stdio',
 \    'log_level': -1,
 \    'suppress_stderr': v:true,
 \  }
 \}
```

The commits prior to 22ad743 were suppressing standard errors as indicated by my `lsc_server_commands`. It would be nice to restore the previous behaviour, I personally get distracted by that output.

Best regards.

**Comment by natebosch** [comment]
Yeah the original behavior was to output all `stderr`, then when I added the suppress option the intention was to only suppress after the server was started, and to emit before that since an error there was more likely to be related to fatal errors.

I think for now I can skip the extra logic around startup. In recent experiences it hasn't helped at all for diagnosing problems anyway. In the long term I plan on dropping the option altogether and always sending `stderr` to a file that you could optionally open if you need to see it. https://github.com/natebosch/vim-lsc/issues/213#issuecomment-631279076

**Comment by bluz71** [comment]
Thanks Nate.
