### ISSUE TITLE
Add configuration option to autocomplete only after a trigger character

### ISSUE THREAD

**Issue by natebosch** [natebosch/vim-lsc#299]
Today there are 2 situations where the plugin will ask for completions automatically:

- 3 word characters have been typed.
- A trigger character (as specified by the server) is typed. For instances typing the `.` following a variable name triggers completions for methods available on that variable.

The Dart server is particular sends a _lot_ of suggestions in the former case. See https://github.com/natebosch/vim-lsc/issues/291#issuecomment-640407193

We could extend the `g:lsc_auto_complete` configuration. A setting of `v:true` or `1` enables all autocomplete, a setting of `v:false` or `0` disables all autocomplete, and a setting of `2` _could_ enable autocomplete for just trigger characters. Manual completion could still be triggered manually using the normal vim complete keybinds as long as the `completefunc` is set, which it is with `g:lsc_auto_map = v:true`.

**Comment by bluz71** [comment]
Hello Nate,

As mentioned in [#291 ](https://github.com/natebosch/vim-lsc/issues/291) I don't personally have a want for this option. But I will instead offer a slightly different refinement that I would use.

When dealing with Dart/Flutter with its huge API surface, auto-completion of types is hugely beneficial. I want `Mat` to expand to `Material****`. Manual triggering would be a chore.

However, auto-completing `ret` into `return` is not that beneficial. In fact, the slight pause in Dart on slow machines is annoying.

So a per-language option to limit auto-completion to `Types` and after `periods` could be handy. Types in the languages of interest to myself always start with a Capital.

In my case I would probably enable that for Dart, but not for JavaScript or Ruby. The latter two have no stutter even on slow machines, likely due to them not sending huge lists to filter (1,200 vs 5,600 as noted for TypeScript LS vs Dart LS).

If Dart LSP was faster I probably wouldn't use this Types-and-Period-only refinement either. So if your fuzzy matching implementation also made strict-prefix matching faster due to using Lua to filter large lists then maybe none of this would be necessary?

If Lua-izing fuzzy/prefix is a ways away then maybe Types-and-Periods-only is a decent interim step.

Auto-completing just for periods is not desired for my workflow.

**Comment by natebosch** [comment]
Thanks for the feedback! I'll keep this open in case someone else discovers it and wants to advocate for it, or it turns into something I want to try anyway 😄

**Comment by bluz71** [comment]
Seems reasonable to wait and see.

My gut tells me that few to none will want this. Either you want auto-completion (globally) or you don't.

LSC already has `g:lsc_autocomplete_length` (defaulting to three). A user could set that to 50 to achieve the same effect as this issue could they not.

Personally I like and use the default of 3, nearly all the alternative LSP/completion plugins trigger after 1. A nice benefit of LSC.

**Comment by natebosch** [comment]
As it turns out I had already implemented support for just this when I added the `g:lsc_autocomplete_length` setting. A value of `0` or `v:false` will already disable word character completion, leaving only trigger character completion. I'll update the docs to call this out in the section discussing `g:lsc_enable_autocomplete`.
