### ISSUE TITLE
Option to not update location list automatically?

### ISSUE THREAD

**Issue by grwlf** [natebosch/vim-lsc#339]
Hi. First of all, thank you for this nice plugin!

This issue is about location window conflicts with other plugins.
I use location window for different purposes, like listing the `git grep` search results or viewing `fzf` search results. Unfortunately, vim-lsc tends to update the location list automatically when I open new file.

Currently, if I navigate through search results and if this process brings me to file with errors, `vim-lsc` updates the location list so I have to switch it back, until I enter another file with errors.

Could you please provide an option to disable auto-update of the location list? It believe it is OK to update it with an explicit command.

**Comment by natebosch** [comment]
Hi!

This is also something I have been thinking about recently since I wanted to use the location list for another purpose temporarily.

I think what I can do is to keep the existing behavior of always populating the location list and keeping it up to date, but I can avoid overwriting another list if the location list is in use for some other purpose.

If you have a chance try out the branch in #342 and let me know how it works for you. My hope is that it should feel like it doesn't get in your way, but is otherwise as present as possible.

If you run a command that uses the location list you can either use `:lolder` to return to the LSC list, or if you aren't sure where in the `:lhistory` stack the LSC list is you can use the command `:LSClientWindowDiagnostics` to restore it. It also won't keep writing list after list and cause old ones to fall off the history stack like it did before, which will make it easier to return to other non-LSC location lists with `:lhistory` and `:lolder` or `:lnewer`.
