### ISSUE TITLE
Some text not readable in popup window

### ISSUE THREAD

**Issue by reinerh** [natebosch/vim-lsc#359]
I'm using vim-lsc (b3d239f) with rust-analyzer.
When I'm opening a popup window with `LSClientShowHover`, it shows information about the function under the cursor like in the following screenshots.
But some of the text is not readable (it's probably printed in the same color as the background?). When selecting the hidden text with the mouse, it's visible, so the text is actually there.
I'm using the default vim colorscheme. Is this a problem with vim-lsc (or its configuration) or something else?
![rust1](https://user-images.githubusercontent.com/3106950/101280862-e2ecf180-37cb-11eb-94d1-60fdf013f8aa.png)
![rust2](https://user-images.githubusercontent.com/3106950/101280865-e5e7e200-37cb-11eb-8c21-3defe2fb5c6e.png)

**Comment by natebosch** [comment]
This is because the default colorscheme in vim uses this bring pink for `Pmenu` highlight group. You can change that highlight group however you prefer, or remove it with `:highlight clear Pmenu`.

You can also disable syntax highlighting in that popup with `let g:lsc_enable_popup_syntax = v:false`. That will make the text look like it would be default in the popup (which still might not look very readable - that pink default is pretty rough if your text color is very light at all...).
