### ISSUE TITLE
Config for Java

### ISSUE THREAD

**Issue by aiezue** [natebosch/vim-lsc#56]
Sorry to bother, but I have tried for two days with [eclipse.jdt.ls](github.com/eclipse/eclipse.jdt.ls) (the java langauge server). Any help with the config?

**Comment by natebosch** [comment]
In https://github.com/eclipse/eclipse.jdt.ls#managing-connection-types it says "To use standard streams(stdin, stdout) of the server process do not set any of the above environment variables and the server will fall back to standard streams." - This is what you'll want for vim-lsc

What OS are you on? My suggestion would be to write a shell script or batch file to wrap up the (apparently extremely lengthy) arguments you need to start the server described here: https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line

I'm afraid I can't help much with getting it running communicating of stdin/stdout beyond pointing to their documentation. You could file an issue there if you get stuck.

Once you have a command you can run which you believe is communicating over stdin/stdout you can try it by redirecting [this file](https://github.com/natebosch/vim-lsc/blob/master/test/initialization_input) to stdin and seeing that it gives you some json output. (It will likely give an error since the root URI path is bogus - that's OK)

`the_command_you_want_to_try < test/initialization_input`

**Comment by cmpadden** [comment]
@aiezue 

I was able to get the Java language server that you referenced working. As Nate suggested, I created a wrapper script that I included on my PATH. 

I downloaded the [latest version](http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz) of the server, and extracted the files. Be sure to update the `jar` and `configuration` properties in the wrapper script with the location that you extracted the server.

Wrapper script:
```sh
#!/bin/sh

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.protocol=true \
     -Dlog.level=ALL \
     -noverify \
     -Xmx1G \
     -jar <UPDATE>/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar \
     -configuration <UPDATE>/config_linux \
     --add-modules=ALL-SYSTEM \
     --add-opens java.base/java.util=ALL-UNNAMED \
     --add-opens java.base/java.lang=ALL-UNNAMED
```

Reference in `vimrc`:
```
let g:lsc_server_commands = {'java': 'jdt_language_server'}
```

I'm using OpenJDK version 9, so your mileage may vary; Hope this helps!

**Comment by aiezue** [comment]
@cmpadden @natebosch Thanks a lot, I have already got it working now. I guess my problem is with the starting script.
