### ISSUE TITLE
Support CTRL-T

### ISSUE THREAD

**Issue by ryanheise** [natebosch/vim-lsc#89]
In the normal behaviour of Vim, CTRL-] jumps to the tag under the cursor, and CTRL-T jumps back to an older entry in the tag stack (useful to go back to where you came from).

Since vim-lsc remaps CTRL-] in a way that doesn't use the tag stack, CTRL-T doesn't work. It would be nice to either make CTRL-] push a tag onto the tag stack or if not, remap CTRL-T as well to emulate the tag stack behaviour in some other way.

**Comment by natebosch** [comment]
I have looked at this before unfortunately vim does not give a way to hook in to the tag behavior. There is an open PR to add a `tagfunc` feature, but it hasn't had any attention for a long time and even that would not work for this use case because we'd need it to allow an asynchronous result.

https://github.com/vim/vim/pull/1628

I have not found that there is any way to edit the tagstack either. I'm worried that chasing down mappings will become a bit of a rathole, and I wouldn't be able to support things like `:pop` or `:tag` at all.

Luckily the current behavior does leave an entry in the jumplist so you can pop back to where you were with CTRL-o (forward with tab or CTRL-i). Will that work for you?

**Comment by pawel-slowik** [comment]
@natebosch the [jedi-vim](https://github.com/davidhalter/jedi-vim/) plugin includes a hackish workaround for this problem [in the `goto` function](https://github.com/davidhalter/jedi-vim/blob/e49638ffc8dc97b108e986308dee1900db92e34e/pythonx/jedi_vim.py#L325).

Basically, after computing the jump destination, the plugin creates a temporary tags file containing only one tag (the one computed earlier) and then executes `tjump` to update the tag stack. After that, the temporary file is removed. A few Vim options need to be changed before and restored after the jump for this to work.

It does the job, but it is also a rather ugly hack, so I don't really know if implementing this is such a good idea. Just letting you know.

**Comment by natebosch** [comment]
@pawel-slowik - I have seen that strategy and spent a little bit of time trying to implement it but I hit a few issues. If I find some time I might give it another shot but it's lower on my priority list than some of the other open issues.

**Comment by pawel-slowik** [comment]
Starting with Vim version 8.1.0519 the tag stack is editable with `gettagstack` / `settagstack`: https://github.com/vim/vim/commit/f49cc60aa802862c595ff619dccc11271633a94b#diff-bea881dfa9626bab7141337b0fcdb23e . This opens up the possibility to support `ctrl + t` without ugly hacks.

Here's my take on it:
```diff
diff --git a/autoload/lsc/reference.vim b/autoload/lsc/reference.vim
index 2c93d13..702abf3 100644
--- a/autoload/lsc/reference.vim
+++ b/autoload/lsc/reference.vim
@@ -19,6 +19,13 @@ function! s:GoToDefinition(result) abort
   let file = lsc#uri#documentPath(location.uri)
   let line = location.range.start.line + 1
   let character = location.range.start.character + 1
+  if exists('*gettagstack') && exists('*settagstack')
+    let from = [bufnr('%'), line('.'), col('.'), 0]
+    let tagname = expand('<cword>')
+    let winid = win_getid()
+    call settagstack(winid, {'items': [{'from': from, 'tagname': tagname}]}, 'a')
+    call settagstack(winid, {'curidx': len(gettagstack(winid)['items']) + 1})
+  endif
   call s:goTo(file, line, character)
 endfunction

```
And it works, provided that you compile latest Vim from source.

**Comment by natebosch** [comment]
@pawel-slowik - awesome!

Want to open a PR? It'll be a few days before I can test it but this looks like the implementation I'd want to use.

**Comment by pawel-slowik** [comment]
To be honest, I'm not even sure if that's the correct way of using the new stack functions. They are so new that you can't just copy some lines from another plugin (which is my usual way of Vim scripting), because nobody seems to be using them yet.

So my comment was more of a _"it can be done now, hope some competent gets to it"_ rather than _"here, I've done it"_. Hence no PR.

Having said that, I've been using vim-lsc with the patch applied for about a week now and 1) it works as expected 2) nothing broke. So we might as well go with it for now and improve / fix later. PR: https://github.com/natebosch/vim-lsc/pull/117
